# Generated by Django 4.1.13 on 2025-07-23 14:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('has_write_access', 'Write permission: can add and update observations'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password_unuseable_fl', models.BooleanField(default=False, help_text='If true, password requires changing before login')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'auth_user_profile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('api_write_access', models.BooleanField(default=False, help_text='Does the group have write access to the API?')),
                ('token_expiration_time', models.DurationField(default=datetime.timedelta(days=1), help_text='in days, default 1 day (24*60*60 seconds)')),
                ('description', models.TextField(blank=True, help_text='What is the group for?')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.group')),
            ],
            options={
                'verbose_name': 'Group Profile',
                'verbose_name_plural': 'Group Profiles',
                'db_table': 'auth_group_profile',
                'managed': True,
            },
        ),
    ]
