# Generated by Django 4.1.13 on 2024-10-29 11:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token_expiration_time', models.DurationField(default=datetime.timedelta(days=1), help_text='in days, default 1 day (24*60*60 seconds)')),
                ('description', models.TextField(blank=True, help_text='What is the group for?')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.group')),
            ],
            options={
                'verbose_name': 'Group Profile',
                'verbose_name_plural': 'Group Profiles',
                'db_table': 'auth_group_profile',
                'managed': True,
            },
        ),
    ]
