# Generated by Django 4.1.13 on 2025-07-31 09:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(
                upload_to='profile_pics',
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=['gif', 'jpeg', 'jpg', 'png']
                    )
                ],
                blank=True,
                null=True,
                help_text='Optional. Upload a profile image (.gif, .png, .jpg).'
            ),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image_b64',
            field=models.TextField(
                blank=True,
                null=True
            ),
        ),
    ]
