drop table if exists sherlock_crossmatches;

CREATE TABLE `sherlock_crossmatches` (
  `transient_object_id` bigint(20) unsigned DEFAULT NULL,
  `catalogue_object_id` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
  `catalogue_table_id` smallint(5) unsigned DEFAULT NULL,
  `separationArcsec` float DEFAULT NULL,
  `northSeparationArcsec` float DEFAULT NULL,
  `eastSeparationArcsec` float DEFAULT NULL,
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `z` float DEFAULT NULL,
  `scale` float DEFAULT NULL,
  `distance` float DEFAULT NULL,
  `distance_modulus` float DEFAULT NULL,
  `photoZ` float DEFAULT NULL,
  `photoZErr` float DEFAULT NULL,
  `association_type` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
  `dateCreated` datetime DEFAULT NULL,
  `physical_separation_kpc` float DEFAULT NULL,
  `catalogue_object_type` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
  `catalogue_object_subtype` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
  `association_rank` int(11) DEFAULT NULL,
  `catalogue_table_name` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `catalogue_view_name` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `rank` int(11) DEFAULT NULL,
  `rankScore` float DEFAULT NULL,
  `search_name` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `major_axis_arcsec` float DEFAULT NULL,
  `direct_distance` float DEFAULT NULL,
  `direct_distance_scale` float DEFAULT NULL,
  `direct_distance_modulus` float DEFAULT NULL,
  `raDeg` double DEFAULT NULL,
  `decDeg` double DEFAULT NULL,
  `original_search_radius_arcsec` float DEFAULT NULL,
  `catalogue_view_id` int(11) DEFAULT NULL,
  `U` float DEFAULT NULL,
  `UErr` float DEFAULT NULL,
  `B` float DEFAULT NULL,
  `BErr` float DEFAULT NULL,
  `V` float DEFAULT NULL,
  `VErr` float DEFAULT NULL,
  `R` float DEFAULT NULL,
  `RErr` float DEFAULT NULL,
  `I` float DEFAULT NULL,
  `IErr` float DEFAULT NULL,
  `J` float DEFAULT NULL,
  `JErr` float DEFAULT NULL,
  `H` float DEFAULT NULL,
  `HErr` float DEFAULT NULL,
  `K` float DEFAULT NULL,
  `KErr` float DEFAULT NULL,
  `_u` float DEFAULT NULL,
  `_uErr` float DEFAULT NULL,
  `_g` float DEFAULT NULL,
  `_gErr` float DEFAULT NULL,
  `_r` float DEFAULT NULL,
  `_rErr` float DEFAULT NULL,
  `_i` float DEFAULT NULL,
  `_iErr` float DEFAULT NULL,
  `_z` float DEFAULT NULL,
  `_zErr` float DEFAULT NULL,
  `_y` float DEFAULT NULL,
  `_yErr` float DEFAULT NULL,
  `G` float DEFAULT NULL,
  `GErr` float DEFAULT NULL,
  `unkMag` float DEFAULT NULL,
  `unkMagErr` float DEFAULT NULL,
  `dateLastModified` datetime DEFAULT NULL,
  `updated` tinyint(4) DEFAULT '0',
  `classificationReliability` tinyint(4) DEFAULT NULL,
  `transientAbsMag` float DEFAULT NULL,
  `merged_rank` tinyint(4) DEFAULT NULL,
  `W1` float DEFAULT NULL,
  `W1Err` float DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `key_transient_object_id` (`transient_object_id`),
  KEY `key_catalogue_object_id` (`catalogue_object_id`),
  KEY `idx_separationArcsec` (`separationArcsec`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
